development:
  bucket: wedding-dev
  access_key_id: AKIAJSKKP3V7P4JM7IQQ
  secret_access_key: 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
test:
  bucket: wedding-dev
  access_key_id: AKIAJSKKP3V7P4JM7IQQ
  secret_access_key: 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
production:
  bucket: wedding
  access_key_id: AKIAJSKKP3V7P4JM7IQQ
  secret_access_key: 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
